In [1]:
import numpy as np

In [2]:
np.fromfunction(lambda x,y : x*y,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [3]:
iterable=(i*i for i in range(5))
iterable

<generator object <genexpr> at 0x7fc45d2bedd0>

In [4]:
np.iterable(iterable)

True

In [5]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [6]:
np.fromstring("123 123",sep=" ")

array([123., 123.])

In [7]:
np.fromstring("123,1230",sep=",")

array([ 123., 1230.])

In [8]:
l=list(range(2,20,2))
ar=np.array(l)
ar

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
ar.ndim

1

In [10]:
ar.size

9

In [11]:
ar.dtype

dtype('int64')

In [12]:
np.arange(2.3,5.4,0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [13]:
list(np.arange(1,2.5,0.5))

[1.0, 1.5, 2.0]

In [14]:
np.linspace(1,10,100)
# will generate 100 data samples

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
ar=np.zeros((2,3,4))
# np.zeros(number_of_matrices,rows,columns)
ar.ndim

3

In [18]:
np.ones((2,3))+7

array([[8., 8., 8.],
       [8., 8., 8.]])

In [19]:
np.empty((5,5))

array([[2.23688261e-316, 0.00000000e+000, 9.82157975e+252,
        8.89489936e+252, 6.01346954e-154],
       [6.01347002e-154, 6.01347002e-154, 6.01347002e-154,
        9.08366793e+223, 1.14177168e+243],
       [2.45126797e+198, 1.06083187e-153, 2.35625393e+251,
        6.01334511e-154, 6.01347002e-154],
       [6.01347002e-154, 6.01347002e-154, 1.88556770e+122,
        4.96820036e+180, 6.80600993e+212],
       [1.10317376e+217, 1.19490107e+190, 2.06642651e+161,
        5.44760669e-109, 7.54400329e-315]])

In [20]:
np.eye(4)
# the identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [22]:
np.logspace(2,10,10)

array([1.00000000e+02, 7.74263683e+02, 5.99484250e+03, 4.64158883e+04,
       3.59381366e+05, 2.78255940e+06, 2.15443469e+07, 1.66810054e+08,
       1.29154967e+09, 1.00000000e+10])

In [23]:
arr=np.random.randn(3,5)
# randaom data samples from the normal distribution
arr

array([[-0.47556357, -0.47603564,  0.16694444,  0.63663936, -0.8386198 ],
       [-0.03458052, -0.01434434,  0.70024074,  2.1104513 , -1.01812111],
       [-0.94552034, -0.11585844,  0.12342077, -1.75226036, -0.66683986]])

In [24]:
np.random.rand(2,5)
# random data values

array([[0.71843011, 0.09559476, 0.63778128, 0.78144131, 0.82887975],
       [0.84923508, 0.65879814, 0.4051937 , 0.87951414, 0.27411541]])

In [25]:
import pandas as pd

In [26]:
pd.DataFrame(arr)

0         1         2         3         4
0 -0.475564 -0.476036  0.166944  0.636639 -0.838620
1 -0.034581 -0.014344  0.700241  2.110451 -1.018121
2 -0.945520 -0.115858  0.123421 -1.752260 -0.666840

In [27]:
np.random.randint(1,100,(3,4))
# will return the integers within the spacefied range

array([[33, 48, 56, 25],
       [79, 59,  9, 44],
       [ 4, 66, 65, 68]])

In [28]:
pd.DataFrame(np.random.randint(1,100,(500,500)))

0    1    2    3    4    5    6    7    8    9    ...  490  491  492  \
0     77   49   39   14   23   72   93   19   87   19  ...   99   56   70   
1     22   55   78   11   66   28   55   69   31   57  ...   58   58   24   
2     13   52   63   75   47   10   87   88   54    8  ...   92   14   89   
3     36   60   14   23   76   42   65   68   20   89  ...   97   45   42   
4     72   15   78   76   86   32   51   83    3   68  ...   42   40   88   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
495   77   56   68   32   72   20   46    3   56   73  ...   66   19   48   
496   77   38   54   45   58   92   38   36   60   97  ...   15   63   48   
497   15   98   25   67   68   49   85   96   76   52  ...   26    1   90   
498   21   32    8   10   50   43   81   59   65   39  ...   63   55   34   
499   95    3    5   44   68   40   11   95   69   70  ...    4   92   44   

     493  494  495  496  497  498  499  
0     96   31   81   67   75   58   52  
1     61   55   57   51   65   67   78  
2     87   14   42   30   70   67   63  
3     83   29   40   77   26   29   45  
4     60   40   50   27   32   13   38  
..   ...  ...  ...  ...  ...  ...  ...  
495   20   51   88   77    1   51   27  
496   22   36   47   43   63   17   57  
497   75   87   15   15   57   91   27  
498   43    6   11   20   21   66   15  
499   97   80   40   73   70   30   35  

[500 rows x 500 columns]

In [29]:
arr.reshape(5,-1)

array([[-0.47556357, -0.47603564,  0.16694444],
       [ 0.63663936, -0.8386198 , -0.03458052],
       [-0.01434434,  0.70024074,  2.1104513 ],
       [-1.01812111, -0.94552034, -0.11585844],
       [ 0.12342077, -1.75226036, -0.66683986]])

In [30]:
arr.reshape(3,-1)

array([[-0.47556357, -0.47603564,  0.16694444,  0.63663936, -0.8386198 ],
       [-0.03458052, -0.01434434,  0.70024074,  2.1104513 , -1.01812111],
       [-0.94552034, -0.11585844,  0.12342077, -1.75226036, -0.66683986]])

In [31]:
arr=np.random.randint(1,100,(50,50))
arr

array([[12, 27, 15, ..., 75, 87, 92],
       [97, 74, 99, ..., 85, 52, 50],
       [42, 85, 33, ..., 64, 33, 31],
       ...,
       [23, 75, 54, ..., 91, 71, 35],
       [36, 75, 77, ..., 39, 29, 68],
       [98, 22, 25, ..., 71, 13, 43]])

In [32]:
len(arr[arr>50])/(2500)

0.4936

In [33]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [34]:
arr1

array([[5, 9, 7],
       [1, 6, 3],
       [8, 8, 3]])

In [35]:
arr2

array([[4, 4, 7],
       [3, 7, 8],
       [4, 9, 1]])

In [36]:
arr1+arr2

array([[ 9, 13, 14],
       [ 4, 13, 11],
       [12, 17,  4]])

In [37]:
arr1*arr2
# element wise multeplication

array([[20, 36, 49],
       [ 3, 42, 24],
       [32, 72,  3]])

In [38]:
arr1@arr2
# Matrix multelication

array([[ 75, 146, 114],
       [ 34,  73,  58],
       [ 68, 115, 123]])

In [39]:
arr1**2

array([[25, 81, 49],
       [ 1, 36,  9],
       [64, 64,  9]])

In [40]:
arr=np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
l=list(range(5))
l

[0, 1, 2, 3, 4]

In [42]:
arr+l

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [43]:
row=np.array(l)
row.shape

(5,)

In [44]:
arr+row
# row wise broadcasting

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [45]:
col=np.array([l])
arr+col.T
# Now the Broadcasting will be column wise

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [46]:
arr1=np.random.randint(1,10,(5,5))
arr1

array([[4, 1, 6, 7, 8],
       [2, 6, 6, 9, 2],
       [7, 1, 4, 3, 5],
       [6, 4, 8, 7, 2],
       [8, 9, 2, 5, 4]])

In [47]:
np.sqrt(arr1)

array([[2.        , 1.        , 2.44948974, 2.64575131, 2.82842712],
       [1.41421356, 2.44948974, 2.44948974, 3.        , 1.41421356],
       [2.64575131, 1.        , 2.        , 1.73205081, 2.23606798],
       [2.44948974, 2.        , 2.82842712, 2.64575131, 1.41421356],
       [2.82842712, 3.        , 1.41421356, 2.23606798, 2.        ]])

In [48]:
np.log10(arr1)

array([[0.60205999, 0.        , 0.77815125, 0.84509804, 0.90308999],
       [0.30103   , 0.77815125, 0.77815125, 0.95424251, 0.30103   ],
       [0.84509804, 0.        , 0.60205999, 0.47712125, 0.69897   ],
       [0.77815125, 0.60205999, 0.90308999, 0.84509804, 0.30103   ],
       [0.90308999, 0.95424251, 0.30103   , 0.69897   , 0.60205999]])

In [51]:
arr=np.exp(arr1)
arr

array([[5.45981500e+01, 2.71828183e+00, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03],
       [7.38905610e+00, 4.03428793e+02, 4.03428793e+02, 8.10308393e+03,
        7.38905610e+00],
       [1.09663316e+03, 2.71828183e+00, 5.45981500e+01, 2.00855369e+01,
        1.48413159e+02],
       [4.03428793e+02, 5.45981500e+01, 2.98095799e+03, 1.09663316e+03,
        7.38905610e+00],
       [2.98095799e+03, 8.10308393e+03, 7.38905610e+00, 1.48413159e+02,
        5.45981500e+01]])

In [52]:
arr.T

array([[5.45981500e+01, 7.38905610e+00, 1.09663316e+03, 4.03428793e+02,
        2.98095799e+03],
       [2.71828183e+00, 4.03428793e+02, 2.71828183e+00, 5.45981500e+01,
        8.10308393e+03],
       [4.03428793e+02, 4.03428793e+02, 5.45981500e+01, 2.98095799e+03,
        7.38905610e+00],
       [1.09663316e+03, 8.10308393e+03, 2.00855369e+01, 1.09663316e+03,
        1.48413159e+02],
       [2.98095799e+03, 7.38905610e+00, 1.48413159e+02, 7.38905610e+00,
        5.45981500e+01]])

In [55]:
arr.shape

(5, 5)

In [59]:
print(arr.reshape(-1,25),arr.reshape(25,-1))

[[5.45981500e+01 2.71828183e+00 4.03428793e+02 1.09663316e+03
  2.98095799e+03 7.38905610e+00 4.03428793e+02 4.03428793e+02
  8.10308393e+03 7.38905610e+00 1.09663316e+03 2.71828183e+00
  5.45981500e+01 2.00855369e+01 1.48413159e+02 4.03428793e+02
  5.45981500e+01 2.98095799e+03 1.09663316e+03 7.38905610e+00
  2.98095799e+03 8.10308393e+03 7.38905610e+00 1.48413159e+02
  5.45981500e+01]] [[5.45981500e+01]
 [2.71828183e+00]
 [4.03428793e+02]
 [1.09663316e+03]
 [2.98095799e+03]
 [7.38905610e+00]
 [4.03428793e+02]
 [4.03428793e+02]
 [8.10308393e+03]
 [7.38905610e+00]
 [1.09663316e+03]
 [2.71828183e+00]
 [5.45981500e+01]
 [2.00855369e+01]
 [1.48413159e+02]
 [4.03428793e+02]
 [5.45981500e+01]
 [2.98095799e+03]
 [1.09663316e+03]
 [7.38905610e+00]
 [2.98095799e+03]
 [8.10308393e+03]
 [7.38905610e+00]
 [1.48413159e+02]
 [5.45981500e+01]]


In [66]:
# will convert the entire data to onedimension data
print(arr.flatten)
arr.flatten

<built-in method flatten of numpy.ndarray object at 0x7fc3a6507450>


<function ndarray.flatten>

In [67]:
arr.flatten()

array([5.45981500e+01, 2.71828183e+00, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 7.38905610e+00, 4.03428793e+02, 4.03428793e+02,
       8.10308393e+03, 7.38905610e+00, 1.09663316e+03, 2.71828183e+00,
       5.45981500e+01, 2.00855369e+01, 1.48413159e+02, 4.03428793e+02,
       5.45981500e+01, 2.98095799e+03, 1.09663316e+03, 7.38905610e+00,
       2.98095799e+03, 8.10308393e+03, 7.38905610e+00, 1.48413159e+02,
       5.45981500e+01])

In [70]:
arr1=np.expand_dims(arr,axis=1)
print(arr1)
arr1.shape

[[[5.45981500e+01 2.71828183e+00 4.03428793e+02 1.09663316e+03
   2.98095799e+03]]

 [[7.38905610e+00 4.03428793e+02 4.03428793e+02 8.10308393e+03
   7.38905610e+00]]

 [[1.09663316e+03 2.71828183e+00 5.45981500e+01 2.00855369e+01
   1.48413159e+02]]

 [[4.03428793e+02 5.45981500e+01 2.98095799e+03 1.09663316e+03
   7.38905610e+00]]

 [[2.98095799e+03 8.10308393e+03 7.38905610e+00 1.48413159e+02
   5.45981500e+01]]]


(5, 1, 5)

In [71]:
arr1=np.expand_dims(arr,axis=0)
print(arr1)
arr1.shape

[[[5.45981500e+01 2.71828183e+00 4.03428793e+02 1.09663316e+03
   2.98095799e+03]
  [7.38905610e+00 4.03428793e+02 4.03428793e+02 8.10308393e+03
   7.38905610e+00]
  [1.09663316e+03 2.71828183e+00 5.45981500e+01 2.00855369e+01
   1.48413159e+02]
  [4.03428793e+02 5.45981500e+01 2.98095799e+03 1.09663316e+03
   7.38905610e+00]
  [2.98095799e+03 8.10308393e+03 7.38905610e+00 1.48413159e+02
   5.45981500e+01]]]


(1, 5, 5)

In [76]:
arr1=np.expand_dims(arr,axis=2)
print(arr1)
arr1.shape

[[[5.45981500e+01]
  [2.71828183e+00]
  [4.03428793e+02]
  [1.09663316e+03]
  [2.98095799e+03]]

 [[7.38905610e+00]
  [4.03428793e+02]
  [4.03428793e+02]
  [8.10308393e+03]
  [7.38905610e+00]]

 [[1.09663316e+03]
  [2.71828183e+00]
  [5.45981500e+01]
  [2.00855369e+01]
  [1.48413159e+02]]

 [[4.03428793e+02]
  [5.45981500e+01]
  [2.98095799e+03]
  [1.09663316e+03]
  [7.38905610e+00]]

 [[2.98095799e+03]
  [8.10308393e+03]
  [7.38905610e+00]
  [1.48413159e+02]
  [5.45981500e+01]]]


(5, 5, 1)

In [81]:
arr1=arr1.squeeze()
arr1

array([[5.45981500e+01, 2.71828183e+00, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03],
       [7.38905610e+00, 4.03428793e+02, 4.03428793e+02, 8.10308393e+03,
        7.38905610e+00],
       [1.09663316e+03, 2.71828183e+00, 5.45981500e+01, 2.00855369e+01,
        1.48413159e+02],
       [4.03428793e+02, 5.45981500e+01, 2.98095799e+03, 1.09663316e+03,
        7.38905610e+00],
       [2.98095799e+03, 8.10308393e+03, 7.38905610e+00, 1.48413159e+02,
        5.45981500e+01]])

In [83]:
arr1.squeeze()

array([[5.45981500e+01, 2.71828183e+00, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03],
       [7.38905610e+00, 4.03428793e+02, 4.03428793e+02, 8.10308393e+03,
        7.38905610e+00],
       [1.09663316e+03, 2.71828183e+00, 5.45981500e+01, 2.00855369e+01,
        1.48413159e+02],
       [4.03428793e+02, 5.45981500e+01, 2.98095799e+03, 1.09663316e+03,
        7.38905610e+00],
       [2.98095799e+03, 8.10308393e+03, 7.38905610e+00, 1.48413159e+02,
        5.45981500e+01]])

In [93]:
arr=np.random.random(5)
print(arr.repeat(3))
print(np.repeat(arr,3))

[0.65142114 0.65142114 0.65142114 0.80897721 0.80897721 0.80897721
 0.78042608 0.78042608 0.78042608 0.58248594 0.58248594 0.58248594
 0.17449835 0.17449835 0.17449835]
[0.65142114 0.65142114 0.65142114 0.80897721 0.80897721 0.80897721
 0.78042608 0.78042608 0.78042608 0.58248594 0.58248594 0.58248594
 0.17449835 0.17449835 0.17449835]


In [98]:
print(arr)
np.roll(arr,2)

[0.65142114 0.80897721 0.78042608 0.58248594 0.17449835]


array([0.58248594, 0.17449835, 0.65142114, 0.80897721, 0.78042608])

In [100]:
np.diag(arr)

array([[0.65142114, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.80897721, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.78042608, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.58248594, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.17449835]])

In [101]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))
(arr1,arr2)

(array([[3, 4, 2, 6],
        [3, 7, 4, 2],
        [5, 5, 6, 8]]),
 array([[5, 1, 4, 6],
        [5, 3, 1, 1],
        [3, 3, 3, 7]]))

In [102]:
arr1%arr2

array([[3, 0, 2, 0],
       [3, 1, 0, 0],
       [2, 2, 0, 1]])

In [103]:
arr1 & arr2

array([[1, 0, 0, 6],
       [1, 3, 0, 0],
       [1, 1, 2, 0]])

In [104]:
~arr1

array([[-4, -5, -3, -7],
       [-4, -8, -5, -3],
       [-6, -6, -7, -9]])

In [105]:
arr1 | arr2

array([[ 7,  5,  6,  6],
       [ 7,  7,  5,  3],
       [ 7,  7,  7, 15]])

In [106]:
arr1>arr2

array([[False,  True, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [108]:
arr=np.array(["string_of_data","another string if data"])
arr

array(['string_of_data', 'another string if data'], dtype='<U22')

In [109]:
np.char.upper(arr)

array(['STRING_OF_DATA', 'ANOTHER STRING IF DATA'], dtype='<U22')

In [110]:
np.char.capitalize(arr)

array(['String_of_data', 'Another string if data'], dtype='<U22')

In [111]:
np.char.title(arr)

array(['String_Of_Data', 'Another String If Data'], dtype='<U22')

In [112]:
arr1

array([[3, 4, 2, 6],
       [3, 7, 4, 2],
       [5, 5, 6, 8]])

In [114]:
np.sin(arr1)

array([[ 0.14112001, -0.7568025 ,  0.90929743, -0.2794155 ],
       [ 0.14112001,  0.6569866 , -0.7568025 ,  0.90929743],
       [-0.95892427, -0.95892427, -0.2794155 ,  0.98935825]])

In [115]:
np.cos(arr1)

array([[-0.9899925 , -0.65364362, -0.41614684,  0.96017029],
       [-0.9899925 ,  0.75390225, -0.65364362, -0.41614684],
       [ 0.28366219,  0.28366219,  0.96017029, -0.14550003]])

In [116]:
np.tan(arr1)

array([[-0.14254654,  1.15782128, -2.18503986, -0.29100619],
       [-0.14254654,  0.87144798,  1.15782128, -2.18503986],
       [-3.38051501, -3.38051501, -0.29100619, -6.79971146]])

In [117]:
np.tanh(arr1)

array([[0.99505475, 0.9993293 , 0.96402758, 0.99998771],
       [0.99505475, 0.99999834, 0.9993293 , 0.96402758],
       [0.9999092 , 0.9999092 , 0.99998771, 0.99999977]])

In [118]:
np.exp(arr1)

array([[  20.08553692,   54.59815003,    7.3890561 ,  403.42879349],
       [  20.08553692, 1096.63315843,   54.59815003,    7.3890561 ],
       [ 148.4131591 ,  148.4131591 ,  403.42879349, 2980.95798704]])

In [119]:
np.sqrt(arr1)

array([[1.73205081, 2.        , 1.41421356, 2.44948974],
       [1.73205081, 2.64575131, 2.        , 1.41421356],
       [2.23606798, 2.23606798, 2.44948974, 2.82842712]])

In [120]:
np.log10(arr1)

array([[0.47712125, 0.60205999, 0.30103   , 0.77815125],
       [0.47712125, 0.84509804, 0.60205999, 0.30103   ],
       [0.69897   , 0.69897   , 0.77815125, 0.90308999]])

In [123]:
arr1.min()

2

In [124]:
np.power(arr1,2)

array([[ 9, 16,  4, 36],
       [ 9, 49, 16,  4],
       [25, 25, 36, 64]])

In [126]:
np.mean(arr1)

4.583333333333333

In [127]:
arr1.mean()

4.583333333333333

In [129]:
np.median(arr1)

4.5

In [131]:
np.std(arr1)

1.846543317180028

In [133]:
arr1.max()

8

In [134]:
np.max(arr1)

8